type Meal {
  id: ID!
  name: String!
  description: String!
  price: Float!
  category: String!
  ingredients: [String!]!
}

input MealFilter {
  category: String
  minPrice: Float
  maxPrice: Float
}

type Query {
  menu(filter: MealFilter): [Meal]!
}

type Mutation {
  validateOrder(order: OrderInput!): String!
}
